controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

telegram:
    resource: "@BoShurikTelegramBotBundle/Resources/config/routing.php"
    prefix: /webhook
