parameters:
    telegram_bot_username: '%env(TELEGRAM_BOT_USERNAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\OpenAiImageService:
        arguments:
            $httpClient: '@openai.client'

    App\Service\StickerService:
        arguments:
            $botUsername: '%telegram_bot_username%'